FROM python:3.8.9

WORKDIR /bot

COPY . .

ARG SLACK_BOT_TOKEN
ARG SLACK_SIGNING_SECRET
ARG NAVER_CLIENT_ID
ARG NAVER_CLIENT_SECRET
ARG NAVER_RECOGNITION_LANG_CLIENT_ID
ARG NAVER_RECOGNITION_LANG_CLIENT_SECRET

ENV SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
ENV SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
ENV NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
ENV NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
ENV NAVER_RECOGNITION_LANG_CLIENT_ID=${NAVER_RECOGNITION_LANG_CLIENT_ID}
ENV NAVER_RECOGNITION_LANG_CLIENT_SECRET=${NAVER_RECOGNITION_LANG_CLIENT_SECRE}

RUN pip3 install -r requirements.txt

EXPOSE 5000

CMD python3 ./bot.py
