FROM python:3.8.9

WORKDIR /bot
COPY . .

ARG SLACK_BOT_TOKEN
ARG SLACK_SIGNING_SECRET
ARG DEV_SLACK_BOT_TOKEN
ARG DEV_SLACK_SIGNING_SECRET
ARG NAVER_CLIENT_ID
ARG NAVER_CLIENT_SECRET
ARG NAVER_RECOGNITION_LANG_CLIENT_ID
ARG NAVER_RECOGNITION_LANG_CLIENT_SECRET
ARG JAVICE_ENV

ENV SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
ENV SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
ENV DEV_SLACK_BOT_TOKEN=${DEV_SLACK_BOT_TOKEN}
ENV DEV_SLACK_SIGNING_SECRET=${DEV_SLACK_SIGNING_SECRET}
ENV JAVICE_ENV=${JAVICE_ENV}
ENV NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
ENV NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
ENV NAVER_RECOGNITION_LANG_CLIENT_ID=${NAVER_RECOGNITION_LANG_CLIENT_ID}
ENV NAVER_RECOGNITION_LANG_CLIENT_SECRET=${NAVER_RECOGNITION_LANG_CLIENT_SECRET}

RUN pip3 install -r requirements

EXPOSE 5000

CMD python3 ./wsgi.py
